/*
PostgreSQL schema for the BTS aircraft turnaround project.

The import uses two tables:
1. stg_on_time_performance keeps every CSV column as text so the raw BTS file
   loads without fighting type conversion or the trailing blank column.
2. raw_on_time_performance keeps only the fields used in the analysis, with
   practical data types.
*/

DROP VIEW IF EXISTS v_aircraft_turnarounds;
DROP VIEW IF EXISTS v_completed_flights;
DROP TABLE IF EXISTS raw_on_time_performance;
DROP TABLE IF EXISTS stg_on_time_performance;

CREATE TABLE stg_on_time_performance (
    year text,
    quarter text,
    month text,
    dayofmonth text,
    dayofweek text,
    flightdate text,
    reporting_airline text,
    dot_id_reporting_airline text,
    iata_code_reporting_airline text,
    tail_number text,
    flight_number_reporting_airline text,
    originairportid text,
    originairportseqid text,
    origincitymarketid text,
    origin text,
    origincityname text,
    originstate text,
    originstatefips text,
    originstatename text,
    originwac text,
    destairportid text,
    destairportseqid text,
    destcitymarketid text,
    dest text,
    destcityname text,
    deststate text,
    deststatefips text,
    deststatename text,
    destwac text,
    crsdeptime text,
    deptime text,
    depdelay text,
    depdelayminutes text,
    depdel15 text,
    departuredelaygroups text,
    deptimeblk text,
    taxiout text,
    wheelsoff text,
    wheelson text,
    taxiin text,
    crsarrtime text,
    arrtime text,
    arrdelay text,
    arrdelayminutes text,
    arrdel15 text,
    arrivaldelaygroups text,
    arrtimeblk text,
    cancelled text,
    cancellationcode text,
    diverted text,
    crselapsedtime text,
    actualelapsedtime text,
    airtime text,
    flights text,
    distance text,
    distancegroup text,
    carrierdelay text,
    weatherdelay text,
    nasdelay text,
    securitydelay text,
    lateaircraftdelay text,
    firstdeptime text,
    totaladdgtime text,
    longestaddgtime text,
    divairportlandings text,
    divreacheddest text,
    divactualelapsedtime text,
    divarrdelay text,
    divdistance text,
    div1airport text,
    div1airportid text,
    div1airportseqid text,
    div1wheelson text,
    div1totalgtime text,
    div1longestgtime text,
    div1wheelsoff text,
    div1tailnum text,
    div2airport text,
    div2airportid text,
    div2airportseqid text,
    div2wheelson text,
    div2totalgtime text,
    div2longestgtime text,
    div2wheelsoff text,
    div2tailnum text,
    div3airport text,
    div3airportid text,
    div3airportseqid text,
    div3wheelson text,
    div3totalgtime text,
    div3longestgtime text,
    div3wheelsoff text,
    div3tailnum text,
    div4airport text,
    div4airportid text,
    div4airportseqid text,
    div4wheelson text,
    div4totalgtime text,
    div4longestgtime text,
    div4wheelsoff text,
    div4tailnum text,
    div5airport text,
    div5airportid text,
    div5airportseqid text,
    div5wheelson text,
    div5totalgtime text,
    div5longestgtime text,
    div5wheelsoff text,
    div5tailnum text,
    extra_blank_column text
);

CREATE TABLE raw_on_time_performance (
    year integer,
    quarter integer,
    month integer,
    dayofmonth integer,
    dayofweek integer,
    flightdate date,
    reporting_airline text,
    dot_id_reporting_airline integer,
    iata_code_reporting_airline text,
    tail_number text,
    flight_number_reporting_airline text,
    originairportid integer,
    originairportseqid integer,
    origincitymarketid integer,
    origin text,
    origincityname text,
    originstate text,
    originstatefips text,
    originstatename text,
    originwac integer,
    destairportid integer,
    destairportseqid integer,
    destcitymarketid integer,
    dest text,
    destcityname text,
    deststate text,
    deststatefips text,
    deststatename text,
    destwac integer,
    crsdeptime text,
    deptime text,
    depdelay numeric,
    depdelayminutes numeric,
    depdel15 numeric,
    departuredelaygroups integer,
    deptimeblk text,
    taxiout numeric,
    wheelsoff text,
    wheelson text,
    taxiin numeric,
    crsarrtime text,
    arrtime text,
    arrdelay numeric,
    arrdelayminutes numeric,
    arrdel15 numeric,
    arrivaldelaygroups integer,
    arrtimeblk text,
    cancelled numeric,
    cancellationcode text,
    diverted numeric,
    crselapsedtime numeric,
    actualelapsedtime numeric,
    airtime numeric,
    flights numeric,
    distance numeric,
    distancegroup integer,
    carrierdelay numeric,
    weatherdelay numeric,
    nasdelay numeric,
    securitydelay numeric,
    lateaircraftdelay numeric
);
